/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parameters.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parameters.pb-c.h"
void   orbiterkep__param_min_max__init
                     (Orbiterkep__ParamMinMax         *message)
{
  static Orbiterkep__ParamMinMax init_value = ORBITERKEP__PARAM_MIN_MAX__INIT;
  *message = init_value;
}
size_t orbiterkep__param_min_max__get_packed_size
                     (const Orbiterkep__ParamMinMax *message)
{
  assert(message->base.descriptor == &orbiterkep__param_min_max__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orbiterkep__param_min_max__pack
                     (const Orbiterkep__ParamMinMax *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orbiterkep__param_min_max__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orbiterkep__param_min_max__pack_to_buffer
                     (const Orbiterkep__ParamMinMax *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orbiterkep__param_min_max__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orbiterkep__ParamMinMax *
       orbiterkep__param_min_max__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orbiterkep__ParamMinMax *)
     protobuf_c_message_unpack (&orbiterkep__param_min_max__descriptor,
                                allocator, len, data);
}
void   orbiterkep__param_min_max__free_unpacked
                     (Orbiterkep__ParamMinMax *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orbiterkep__param_min_max__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orbiterkep__parameters__init
                     (Orbiterkep__Parameters         *message)
{
  static Orbiterkep__Parameters init_value = ORBITERKEP__PARAMETERS__INIT;
  *message = init_value;
}
size_t orbiterkep__parameters__get_packed_size
                     (const Orbiterkep__Parameters *message)
{
  assert(message->base.descriptor == &orbiterkep__parameters__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orbiterkep__parameters__pack
                     (const Orbiterkep__Parameters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orbiterkep__parameters__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orbiterkep__parameters__pack_to_buffer
                     (const Orbiterkep__Parameters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orbiterkep__parameters__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orbiterkep__Parameters *
       orbiterkep__parameters__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orbiterkep__Parameters *)
     protobuf_c_message_unpack (&orbiterkep__parameters__descriptor,
                                allocator, len, data);
}
void   orbiterkep__parameters__free_unpacked
                     (Orbiterkep__Parameters *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orbiterkep__parameters__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor orbiterkep__param_min_max__field_descriptors[2] =
{
  {
    "min",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orbiterkep__ParamMinMax, has_min),
    offsetof(Orbiterkep__ParamMinMax, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orbiterkep__ParamMinMax, has_max),
    offsetof(Orbiterkep__ParamMinMax, max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orbiterkep__param_min_max__field_indices_by_name[] = {
  1,   /* field[1] = max */
  0,   /* field[0] = min */
};
static const ProtobufCIntRange orbiterkep__param_min_max__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor orbiterkep__param_min_max__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orbiterkep.ParamMinMax",
  "ParamMinMax",
  "Orbiterkep__ParamMinMax",
  "orbiterkep",
  sizeof(Orbiterkep__ParamMinMax),
  2,
  orbiterkep__param_min_max__field_descriptors,
  orbiterkep__param_min_max__field_indices_by_name,
  1,  orbiterkep__param_min_max__number_ranges,
  (ProtobufCMessageInit) orbiterkep__param_min_max__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orbiterkep__parameters__field_descriptors[18] =
{
  {
    "planets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Orbiterkep__Parameters, n_planets),
    offsetof(Orbiterkep__Parameters, planets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "single_objective_algos",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Orbiterkep__Parameters, n_single_objective_algos),
    offsetof(Orbiterkep__Parameters, single_objective_algos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multi_objective_algos",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Orbiterkep__Parameters, n_multi_objective_algos),
    offsetof(Orbiterkep__Parameters, multi_objective_algos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t0",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orbiterkep__Parameters, t0),
    &orbiterkep__param_min_max__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tof",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orbiterkep__Parameters, tof),
    &orbiterkep__param_min_max__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vinf",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orbiterkep__Parameters, vinf),
    &orbiterkep__param_min_max__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "problem",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orbiterkep__Parameters, problem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_trials",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Orbiterkep__Parameters, has_n_trials),
    offsetof(Orbiterkep__Parameters, n_trials),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_gen",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Orbiterkep__Parameters, has_n_gen),
    offsetof(Orbiterkep__Parameters, n_gen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dep_altitude",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orbiterkep__Parameters, has_dep_altitude),
    offsetof(Orbiterkep__Parameters, dep_altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arr_altitude",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orbiterkep__Parameters, has_arr_altitude),
    offsetof(Orbiterkep__Parameters, arr_altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_deltav",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orbiterkep__Parameters, has_max_deltav),
    offsetof(Orbiterkep__Parameters, max_deltav),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_dep_vinf",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_add_dep_vinf),
    offsetof(Orbiterkep__Parameters, add_dep_vinf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_arr_vinf",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_add_arr_vinf),
    offsetof(Orbiterkep__Parameters, add_arr_vinf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_spice",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_use_spice),
    offsetof(Orbiterkep__Parameters, use_spice),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "circularize",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_circularize),
    offsetof(Orbiterkep__Parameters, circularize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multi_objective",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_multi_objective),
    offsetof(Orbiterkep__Parameters, multi_objective),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_db",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orbiterkep__Parameters, has_use_db),
    offsetof(Orbiterkep__Parameters, use_db),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orbiterkep__parameters__field_indices_by_name[] = {
  13,   /* field[13] = add_arr_vinf */
  12,   /* field[12] = add_dep_vinf */
  10,   /* field[10] = arr_altitude */
  15,   /* field[15] = circularize */
  9,   /* field[9] = dep_altitude */
  11,   /* field[11] = max_deltav */
  16,   /* field[16] = multi_objective */
  2,   /* field[2] = multi_objective_algos */
  8,   /* field[8] = n_gen */
  7,   /* field[7] = n_trials */
  0,   /* field[0] = planets */
  6,   /* field[6] = problem */
  1,   /* field[1] = single_objective_algos */
  3,   /* field[3] = t0 */
  4,   /* field[4] = tof */
  17,   /* field[17] = use_db */
  14,   /* field[14] = use_spice */
  5,   /* field[5] = vinf */
};
static const ProtobufCIntRange orbiterkep__parameters__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor orbiterkep__parameters__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orbiterkep.Parameters",
  "Parameters",
  "Orbiterkep__Parameters",
  "orbiterkep",
  sizeof(Orbiterkep__Parameters),
  18,
  orbiterkep__parameters__field_descriptors,
  orbiterkep__parameters__field_indices_by_name,
  1,  orbiterkep__parameters__number_ranges,
  (ProtobufCMessageInit) orbiterkep__parameters__init,
  NULL,NULL,NULL    /* reserved[123] */
};
