/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/solution.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/solution.pb-c.h"
void   pagmo__problem__trans_xtimes__init
                     (Pagmo__Problem__TransXTimes         *message)
{
  static Pagmo__Problem__TransXTimes init_value = PAGMO__PROBLEM__TRANS_XTIMES__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xtimes__get_packed_size
                     (const Pagmo__Problem__TransXTimes *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xtimes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xtimes__pack
                     (const Pagmo__Problem__TransXTimes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xtimes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xtimes__pack_to_buffer
                     (const Pagmo__Problem__TransXTimes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xtimes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXTimes *
       pagmo__problem__trans_xtimes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXTimes *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xtimes__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xtimes__free_unpacked
                     (Pagmo__Problem__TransXTimes *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xtimes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pagmo__problem__trans_xescape__init
                     (Pagmo__Problem__TransXEscape         *message)
{
  static Pagmo__Problem__TransXEscape init_value = PAGMO__PROBLEM__TRANS_XESCAPE__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xescape__get_packed_size
                     (const Pagmo__Problem__TransXEscape *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xescape__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xescape__pack
                     (const Pagmo__Problem__TransXEscape *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xescape__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xescape__pack_to_buffer
                     (const Pagmo__Problem__TransXEscape *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xescape__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXEscape *
       pagmo__problem__trans_xescape__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXEscape *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xescape__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xescape__free_unpacked
                     (Pagmo__Problem__TransXEscape *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xescape__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pagmo__problem__trans_xdsm__init
                     (Pagmo__Problem__TransXDSM         *message)
{
  static Pagmo__Problem__TransXDSM init_value = PAGMO__PROBLEM__TRANS_XDSM__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xdsm__get_packed_size
                     (const Pagmo__Problem__TransXDSM *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xdsm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xdsm__pack
                     (const Pagmo__Problem__TransXDSM *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xdsm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xdsm__pack_to_buffer
                     (const Pagmo__Problem__TransXDSM *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xdsm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXDSM *
       pagmo__problem__trans_xdsm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXDSM *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xdsm__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xdsm__free_unpacked
                     (Pagmo__Problem__TransXDSM *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xdsm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pagmo__problem__trans_xfly_by__init
                     (Pagmo__Problem__TransXFlyBy         *message)
{
  static Pagmo__Problem__TransXFlyBy init_value = PAGMO__PROBLEM__TRANS_XFLY_BY__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xfly_by__get_packed_size
                     (const Pagmo__Problem__TransXFlyBy *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xfly_by__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xfly_by__pack
                     (const Pagmo__Problem__TransXFlyBy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xfly_by__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xfly_by__pack_to_buffer
                     (const Pagmo__Problem__TransXFlyBy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xfly_by__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXFlyBy *
       pagmo__problem__trans_xfly_by__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXFlyBy *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xfly_by__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xfly_by__free_unpacked
                     (Pagmo__Problem__TransXFlyBy *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xfly_by__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pagmo__problem__trans_xarrival__init
                     (Pagmo__Problem__TransXArrival         *message)
{
  static Pagmo__Problem__TransXArrival init_value = PAGMO__PROBLEM__TRANS_XARRIVAL__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xarrival__get_packed_size
                     (const Pagmo__Problem__TransXArrival *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xarrival__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xarrival__pack
                     (const Pagmo__Problem__TransXArrival *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xarrival__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xarrival__pack_to_buffer
                     (const Pagmo__Problem__TransXArrival *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xarrival__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXArrival *
       pagmo__problem__trans_xarrival__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXArrival *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xarrival__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xarrival__free_unpacked
                     (Pagmo__Problem__TransXArrival *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xarrival__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pagmo__problem__trans_xsolution__init
                     (Pagmo__Problem__TransXSolution         *message)
{
  static Pagmo__Problem__TransXSolution init_value = PAGMO__PROBLEM__TRANS_XSOLUTION__INIT;
  *message = init_value;
}
size_t pagmo__problem__trans_xsolution__get_packed_size
                     (const Pagmo__Problem__TransXSolution *message)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xsolution__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pagmo__problem__trans_xsolution__pack
                     (const Pagmo__Problem__TransXSolution *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xsolution__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pagmo__problem__trans_xsolution__pack_to_buffer
                     (const Pagmo__Problem__TransXSolution *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xsolution__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pagmo__Problem__TransXSolution *
       pagmo__problem__trans_xsolution__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pagmo__Problem__TransXSolution *)
     protobuf_c_message_unpack (&pagmo__problem__trans_xsolution__descriptor,
                                allocator, len, data);
}
void   pagmo__problem__trans_xsolution__free_unpacked
                     (Pagmo__Problem__TransXSolution *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pagmo__problem__trans_xsolution__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pagmo__problem__trans_xtimes__field_descriptors[2] =
{
  {
    "planets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Pagmo__Problem__TransXTimes, n_planets),
    offsetof(Pagmo__Problem__TransXTimes, planets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "times",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Pagmo__Problem__TransXTimes, n_times),
    offsetof(Pagmo__Problem__TransXTimes, times),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xtimes__field_indices_by_name[] = {
  0,   /* field[0] = planets */
  1,   /* field[1] = times */
};
static const ProtobufCIntRange pagmo__problem__trans_xtimes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xtimes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXTimes",
  "TransXTimes",
  "Pagmo__Problem__TransXTimes",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXTimes),
  2,
  pagmo__problem__trans_xtimes__field_descriptors,
  pagmo__problem__trans_xtimes__field_indices_by_name,
  1,  pagmo__problem__trans_xtimes__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xtimes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pagmo__problem__trans_xescape__field_descriptors[7] =
{
  {
    "mjd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, mjd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vinf",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, vinf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burn",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, burn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prograde",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, prograde),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outward",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, outward),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plane",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, plane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planet",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXEscape, planet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xescape__field_indices_by_name[] = {
  2,   /* field[2] = burn */
  0,   /* field[0] = mjd */
  4,   /* field[4] = outward */
  5,   /* field[5] = plane */
  6,   /* field[6] = planet */
  3,   /* field[3] = prograde */
  1,   /* field[1] = vinf */
};
static const ProtobufCIntRange pagmo__problem__trans_xescape__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 20, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xescape__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXEscape",
  "TransXEscape",
  "Pagmo__Problem__TransXEscape",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXEscape),
  7,
  pagmo__problem__trans_xescape__field_descriptors,
  pagmo__problem__trans_xescape__field_indices_by_name,
  2,  pagmo__problem__trans_xescape__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xescape__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pagmo__problem__trans_xdsm__field_descriptors[6] =
{
  {
    "mjd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, mjd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vinf",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, vinf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burn",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, burn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prograde",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, prograde),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outward",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, outward),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plane",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXDSM, plane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xdsm__field_indices_by_name[] = {
  2,   /* field[2] = burn */
  0,   /* field[0] = mjd */
  4,   /* field[4] = outward */
  5,   /* field[5] = plane */
  3,   /* field[3] = prograde */
  1,   /* field[1] = vinf */
};
static const ProtobufCIntRange pagmo__problem__trans_xdsm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xdsm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXDSM",
  "TransXDSM",
  "Pagmo__Problem__TransXDSM",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXDSM),
  6,
  pagmo__problem__trans_xdsm__field_descriptors,
  pagmo__problem__trans_xdsm__field_indices_by_name,
  1,  pagmo__problem__trans_xdsm__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xdsm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pagmo__problem__trans_xfly_by__field_descriptors[12] =
{
  {
    "mjd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, mjd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burn",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, burn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prograde",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, prograde),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outward",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, outward),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plane",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, plane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approach_vel",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, approach_vel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "departure_vel",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, departure_vel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outward_angle",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, outward_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inclination",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, inclination),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turning_angle",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, turning_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "periapsis_altitude",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, periapsis_altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planet",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXFlyBy, planet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xfly_by__field_indices_by_name[] = {
  5,   /* field[5] = approach_vel */
  1,   /* field[1] = burn */
  6,   /* field[6] = departure_vel */
  8,   /* field[8] = inclination */
  0,   /* field[0] = mjd */
  3,   /* field[3] = outward */
  7,   /* field[7] = outward_angle */
  10,   /* field[10] = periapsis_altitude */
  4,   /* field[4] = plane */
  11,   /* field[11] = planet */
  2,   /* field[2] = prograde */
  9,   /* field[9] = turning_angle */
};
static const ProtobufCIntRange pagmo__problem__trans_xfly_by__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 20, 11 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xfly_by__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXFlyBy",
  "TransXFlyBy",
  "Pagmo__Problem__TransXFlyBy",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXFlyBy),
  12,
  pagmo__problem__trans_xfly_by__field_descriptors,
  pagmo__problem__trans_xfly_by__field_indices_by_name,
  3,  pagmo__problem__trans_xfly_by__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xfly_by__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pagmo__problem__trans_xarrival__field_descriptors[4] =
{
  {
    "mjd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXArrival, mjd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vinf",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXArrival, vinf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burn",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXArrival, burn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planet",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXArrival, planet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xarrival__field_indices_by_name[] = {
  2,   /* field[2] = burn */
  0,   /* field[0] = mjd */
  3,   /* field[3] = planet */
  1,   /* field[1] = vinf */
};
static const ProtobufCIntRange pagmo__problem__trans_xarrival__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 20, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xarrival__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXArrival",
  "TransXArrival",
  "Pagmo__Problem__TransXArrival",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXArrival),
  4,
  pagmo__problem__trans_xarrival__field_descriptors,
  pagmo__problem__trans_xarrival__field_indices_by_name,
  2,  pagmo__problem__trans_xarrival__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xarrival__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pagmo__problem__trans_xsolution__field_descriptors[8] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Pagmo__Problem__TransXSolution, n_x),
    offsetof(Pagmo__Problem__TransXSolution, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "problem",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXSolution, problem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fuel_cost",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXSolution, fuel_cost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "times",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXSolution, times),
    &pagmo__problem__trans_xtimes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "escape",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXSolution, escape),
    &pagmo__problem__trans_xescape__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsms",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pagmo__Problem__TransXSolution, n_dsms),
    offsetof(Pagmo__Problem__TransXSolution, dsms),
    &pagmo__problem__trans_xdsm__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flybyes",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pagmo__Problem__TransXSolution, n_flybyes),
    offsetof(Pagmo__Problem__TransXSolution, flybyes),
    &pagmo__problem__trans_xfly_by__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arrival",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pagmo__Problem__TransXSolution, arrival),
    &pagmo__problem__trans_xarrival__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pagmo__problem__trans_xsolution__field_indices_by_name[] = {
  7,   /* field[7] = arrival */
  5,   /* field[5] = dsms */
  4,   /* field[4] = escape */
  6,   /* field[6] = flybyes */
  2,   /* field[2] = fuel_cost */
  1,   /* field[1] = problem */
  3,   /* field[3] = times */
  0,   /* field[0] = x */
};
static const ProtobufCIntRange pagmo__problem__trans_xsolution__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor pagmo__problem__trans_xsolution__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pagmo.problem.TransXSolution",
  "TransXSolution",
  "Pagmo__Problem__TransXSolution",
  "pagmo.problem",
  sizeof(Pagmo__Problem__TransXSolution),
  8,
  pagmo__problem__trans_xsolution__field_descriptors,
  pagmo__problem__trans_xsolution__field_indices_by_name,
  1,  pagmo__problem__trans_xsolution__number_ranges,
  (ProtobufCMessageInit) pagmo__problem__trans_xsolution__init,
  NULL,NULL,NULL    /* reserved[123] */
};
